# Generated by Django 5.2.7 on 2026-04-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('online', 'Online'), ('onsite', 'Onsite')], max_length=10)),
                ('batch_type', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends')], max_length=10)),
                ('session_period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('days_pattern', models.CharField(choices=[('mon_wed_fri', 'Mon/Wed/Fri'), ('tue_thu_sat', 'Tue/Thu/Sat'), ('fri_sat', 'Fri/Sat (Weekends)')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration_weeks', models.PositiveIntegerField(default=6)),
                ('max_students', models.PositiveIntegerField(default=20)),
                ('is_published', models.BooleanField(default=False)),
                ('is_full', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='courses.course')),
                ('created_by', models.ForeignKey(limit_choices_to={'profile__role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('time_period', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=10)),
                ('duration_hours', models.PositiveIntegerField(default=3)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduling.batch')),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subject')),
            ],
            options={
                'unique_together': {('batch', 'day', 'time_period')},
            },
        ),
    ]
