# Generated by Django 5.2.7 on 2026-08-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Academy tenant running this batch.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='tenants.tenant'),
        ),
    ]
