# Generated by Django 5.2.7 on 2026-09-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_batch_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='days_pattern',
            field=models.CharField(choices=[('mon_wed_fri', 'Mon / Wed / Fri'), ('tue_thu_fri', 'Tue / Thu / Fri'), ('tue_thu_sat', 'Tue / Thu / Sat'), ('weekend', 'Weekend (Fri & Sat)'), ('fri_sat', 'Fri (4-6pm) & Sat (9am-3pm)'), ('saturday_only', 'Saturday Only')], max_length=20),
        ),
    ]
