# Generated by Django 5.2.7 on 2026-08-07 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_approved_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(default='manual', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='external_attendance_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional ID used by an external attendance system.', max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late'), ('Excused', 'Excused')], max_length=10),
        ),
    ]
