# Generated by Django 5.2.7 on 2026-08-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_attendance_check_in_time_attendance_check_out_time'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attendance',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Academy tenant where attendance occurred.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='registration_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Academy tenant this user belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='tuition_paid',
            field=models.BooleanField(default=False),
        ),
    ]
