# Generated by Django 5.2.7 on 2026-09-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_options_remove_profile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='start_date',
            field=models.DateField(blank=True, help_text='Official cohort or program start date.', null=True),
        ),
    ]
