# Generated by Django 5.2.7 on 2026-09-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor'), ('hod', 'Head of Department'), ('support', 'Support Staff'), ('accountant', 'Accountant')], default='student', max_length=20),
        ),
    ]
