# Generated by Django 5.2.7 on 2026-09-25 20:06

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_profile_role'),
        ('courses', '0003_course_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('active', 'Active Student'), ('summer_alumni', 'Summer Alumni (Inactive)'), ('withdrawn', 'Withdrawn')], default='active', help_text='Active vs Summer Alumni (Restricted to certificate/report until re-enrolled).', max_length=20),
        ),
        migrations.CreateModel(
            name='SummerCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion - Summer CodeCamp', max_length=255)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/summer/')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_id', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('remarks', models.CharField(blank=True, default='Outstanding participation in Summer Boot Camp', max_length=255)),
                ('grade_or_score', models.CharField(blank=True, default='Distinction', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summer_certificates', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Summer Certificate',
                'verbose_name_plural': 'Summer Certificates',
                'ordering': ['-issue_date'],
            },
        ),
    ]
