# Generated by Django 5.2.7 on 2026-09-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_student_status_summercertificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='assigned_tutor',
            field=models.ForeignKey(blank=True, help_text='Assigned teacher or tutor for this student.', limit_choices_to={'profile__role__in': ['instructor', 'hod']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
