# Generated by Django 5.2.7 on 2026-09-26 20:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_assigned_tutor'),
        ('courses', '0003_course_tenant'),
        ('scheduling', '0003_alter_batch_days_pattern'),
        ('tenants', '0004_tenant_director_name_tenant_director_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('active', 'Active Student'), ('completed', 'Completed / Graduated'), ('summer_alumni', 'Summer Alumni (Inactive)'), ('withdrawn', 'Withdrawn')], default='active', help_text='Active vs Summer Alumni (Restricted to certificate/report until re-enrolled).', max_length=20),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate of Completion', max_length=255)),
                ('grade', models.CharField(choices=[('Distinction', 'Distinction / Excellent'), ('Merit', 'Merit / Very Good'), ('Credit', 'Credit / Good'), ('Pass', 'Pass'), ('Participation', 'Certificate of Participation')], default='Merit', max_length=50)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/official/')),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('completion_date', models.DateField(default=django.utils.timezone.localdate)),
                ('reference_id', models.CharField(default=uuid.uuid4, max_length=60, unique=True)),
                ('remarks', models.CharField(blank=True, default='Outstanding completion of all training modules and practical benchmarks.', max_length=255)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='scheduling.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='courses.course')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_official_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
    ]
