# Generated by Django 5.2.7 on 2026-09-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_profile_student_status_certificate'),
        ('courses', '0004_alter_assignment_options_alter_submission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='enrolled_subjects',
            field=models.ManyToManyField(blank=True, help_text='Curriculum subjects this student is enrolled in.', related_name='enrolled_students', to='courses.subject'),
        ),
    ]
