# Generated by Django 5.2.7 on 2026-09-28 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_profile_enrolled_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Dr', 'Dr.'), ('Engr', 'Engr.'), ('Chief', 'Chief'), ('Pastor', 'Pastor'), ('Alhaji', 'Alhaji'), ('Hajiya', 'Hajiya')], default='Mr', max_length=20)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=25)),
                ('whatsapp_number', models.CharField(blank=True, max_length=25)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parent / Guardian',
                'verbose_name_plural': 'Parents / Guardians',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="Student's date of birth.", null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Prefer not to say')], max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='id_card_approved',
            field=models.BooleanField(default=False, help_text="Whether the student's passport and parameters are approved for official ID Card generation."),
        ),
        migrations.AddField(
            model_name='profile',
            name='relationship_to_parent',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Sponsor', 'Sponsor / Relative'), ('Self', 'Self (Independent Adult)')], default='Guardian', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent or guardian of this student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.parent'),
        ),
    ]
