# Generated by Django 5.2.7 on 2026-09-28 22:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_parent_profile_date_of_birth_profile_gender_and_more'),
        ('courses', '0006_subject_is_compulsory'),
        ('scheduling', '0003_alter_batch_days_pattern'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_approval_status',
            field=models.CharField(choices=[('none', 'None'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none', help_text='Status of student course enrollment or change request.', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='course_change_requested_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of latest course selection/change request.', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Agreed tuition concession or scholarship discount.', max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='discount_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for discount e.g. Sibling, Early Bird, Staff Child.', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_batch',
            field=models.ForeignKey(blank=True, help_text='Cohort requested by student awaiting admin approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_students', to='scheduling.batch'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_course',
            field=models.ForeignKey(blank=True, help_text='Course selected or requested by student awaiting admin approval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_students', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('inactive', 'Inactive / Pending Start'), ('active', 'Active Student'), ('alumni', 'Alumni / Completed'), ('completed', 'Completed / Graduated'), ('summer_alumni', 'Summer Alumni (Archived)'), ('withdrawn', 'Withdrawn')], default='inactive', help_text='Student lifecycle status: Inactive, Active, or Alumni.', max_length=20),
        ),
    ]
