# Generated by Django 5.2.7 on 2026-09-26 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_alter_assignment_options_alter_submission_options_and_more'),
        ('scheduling', '0003_alter_batch_days_pattern'),
        ('tenants', '0004_tenant_director_name_tenant_director_signature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('active', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired / Timed Out'), ('flagged', 'Flagged for Tutor Review')], default='pending', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_defense_score', models.FloatField(default=0.0, help_text='0-100 average defense score')),
                ('tutor_reviewed', models.BooleanField(default=False)),
                ('tutor_review_notes', models.TextField(blank=True)),
                ('tutor_override_score', models.FloatField(blank=True, null=True)),
                ('cheating_risk_score', models.FloatField(default=0.0, help_text='0.0 (low risk) to 1.0 (high risk), evaluated from paste velocity + defense-practical mismatch')),
                ('cheating_risk_reason', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defense_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DefenseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('explain', 'Code Explanation & Complexity'), ('predict', 'Predict Output on Mutant Input'), ('modify', 'Modify Edge Case / Refactor')], default='explain', max_length=20)),
                ('prompt', models.TextField(help_text='The defense question posed to the student')),
                ('target_code_snippet', models.TextField(blank=True, help_text='Student code lines or construct referenced by this question')),
                ('options', models.JSONField(blank=True, default=list, help_text="Multiple-choice options if applicable: [{'key': 'A', 'text': '...'}, ...]")),
                ('correct_answer', models.TextField(blank=True, help_text='Expected key or rubric answer')),
                ('student_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0, help_text='Question score (0-100)')),
                ('ai_evaluation_notes', models.TextField(blank=True)),
                ('time_limit_sec', models.IntegerField(default=90, help_text='Time limit in seconds for this question')),
                ('time_spent_sec', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.defensesession')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PracticalProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript (Node.js)'), ('sql', 'SQL (SQLite)')], default='python', max_length=20)),
                ('description', models.TextField(help_text='Problem statement and requirements in Markdown')),
                ('starter_code', models.TextField(blank=True, help_text='Default boilerplate code for student editor')),
                ('solution_template', models.TextField(blank=True, help_text='Reference solution code for verification')),
                ('time_limit_sec', models.FloatField(default=2.0, help_text='Max execution time in seconds per test case')),
                ('memory_limit_mb', models.IntegerField(default=128, help_text='RAM limit in Megabytes')),
                ('weight_practical_pct', models.IntegerField(default=70, help_text='Percentage weight of unit tests (e.g. 70%)')),
                ('weight_defense_pct', models.IntegerField(default=30, help_text='Percentage weight of code defense (e.g. 30%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_problems', to='scheduling.batch')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practical_problems', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, help_text='Academy tenant offering this assessment.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practical_problems', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticalSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_code', models.TextField()),
                ('language', models.CharField(default='python', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft / In Progress'), ('running', 'Running Tests'), ('passed', 'All Tests Passed'), ('partial', 'Partially Passed'), ('failed', 'Tests Failed'), ('error', 'Execution Error / Timeout'), ('defense_pending', 'Defense Pending'), ('completed', 'Completed & Graded')], default='draft', max_length=30)),
                ('practical_score', models.FloatField(default=0.0, help_text='0-100 calculated from test cases')),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_total', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('memory_used_kb', models.FloatField(default=0.0)),
                ('telemetry_paste_detected', models.BooleanField(default=False, help_text='True if a large code block was pasted instantaneously')),
                ('telemetry_paste_chars', models.IntegerField(default=0)),
                ('telemetry_keystrokes', models.IntegerField(default=0)),
                ('telemetry_duration_sec', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.practicalproblem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practical_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='defensesession',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defense_session', to='assessments.practicalsubmission'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Test Case', max_length=150)),
                ('input_data', models.TextField(blank=True, help_text='Input data (stdin or arguments representation)')),
                ('expected_output', models.TextField(help_text='Expected stdout or return value')),
                ('is_hidden', models.BooleanField(default=False, help_text='If True, hidden from students during practice; evaluated upon submission')),
                ('points', models.IntegerField(default=10, help_text='Points allocated to this test case')),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assessments.practicalproblem')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('actual_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('execution_time_ms', models.FloatField(default=0.0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_results', to='assessments.practicalsubmission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='assessments.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='FinalPracticalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practical_score', models.FloatField(default=0.0)),
                ('defense_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0, help_text='Composite weighted score')),
                ('status', models.CharField(choices=[('Distinction', 'Distinction (>= 85%)'), ('Merit', 'Merit (70% - 84%)'), ('Credit', 'Credit (60% - 69%)'), ('Pass', 'Pass (50% - 59%)'), ('Fail', 'Fail (< 50%)'), ('Review Needed', 'Flagged / Tutor Review Needed')], default='Pass', max_length=30)),
                ('certificate_recommendation', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('defense_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_grade', to='assessments.defensesession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_practical_grades', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='assessments.practicalproblem')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grade', to='assessments.practicalsubmission')),
            ],
            options={
                'ordering': ['-calculated_at'],
                'unique_together': {('student', 'problem')},
            },
        ),
    ]
