# Generated by Django 5.2.7 on 2026-04-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('min_team_size', models.PositiveIntegerField(default=1)),
                ('max_team_size', models.PositiveIntegerField(default=4)),
                ('schedule_markdown', models.TextField(blank=True)),
                ('rules_markdown', models.TextField(blank=True)),
                ('prizes_markdown', models.TextField(blank=True)),
                ('theme', models.CharField(choices=[('default', 'Default Theme'), ('punk', 'Hackathon Punk Theme')], default='default', max_length=20)),
                ('reminder_subject', models.CharField(blank=True, max_length=200)),
                ('reminder_body', models.TextField(blank=True, help_text='Use {full_name} for participant name placeholders.')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionJudge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judges', to='competition.competitionedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('track', models.CharField(choices=[('javascripts', 'JavaScript'), ('python', 'Python')], default='javascripts', max_length=50)),
                ('checked_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='competition.competitionedition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionCheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='competition.competitionedition')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.competitionparticipant')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tier', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='competition/sponsors/')),
                ('website', models.URLField(blank=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='competition.competitionedition')),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('track', models.CharField(choices=[('javascripts', 'JavaScript'), ('python', 'Python')], default='javascripts', max_length=50)),
                ('join_code', models.CharField(max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competition.competitionedition')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='competitionparticipant',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='competition.competitionteam'),
        ),
        migrations.CreateModel(
            name='CompetitionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('r1', 'Round 1'), ('r2', 'Round 2'), ('final', 'Final')], default='r1', max_length=10)),
                ('raw_score', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competition.competitionedition')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competition.competitionparticipant')),
            ],
            options={
                'unique_together': {('participant', 'judge', 'round')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='competitionparticipant',
            unique_together={('user', 'edition')},
        ),
    ]
