# Generated by Django 5.2.7 on 2026-08-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_assignment_submission'),
        ('tenants', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Academy tenant offering this course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='tenants.tenant'),
        ),
    ]
