# Generated by Django 5.2.7 on 2026-09-26 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_tenant'),
        ('scheduling', '0003_alter_batch_days_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['week_number', 'due_date']},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='scheduling.batch'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='rubric_template',
            field=models.JSONField(blank=True, default=list, help_text='Rubric criteria definition'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='week_number',
            field=models.PositiveIntegerField(default=1, help_text='Curriculum week number (e.g. 1, 2, 3...)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='letter_grade',
            field=models.CharField(blank=True, choices=[('Distinction', 'Distinction / Excellent'), ('Merit', 'Merit / Very Good'), ('Credit', 'Credit / Good'), ('Pass', 'Pass'), ('Needs Revision', 'Needs Revision')], max_length=50),
        ),
        migrations.AddField(
            model_name='submission',
            name='live_demo_url',
            field=models.URLField(blank=True, help_text='Live URL or deployment link', max_length=300),
        ),
        migrations.AddField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, help_text='Student remarks / self-reflection'),
        ),
        migrations.AddField(
            model_name='submission',
            name='repo_url',
            field=models.URLField(blank=True, help_text='GitHub or source repository link', max_length=300),
        ),
        migrations.AddField(
            model_name='submission',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Points awarded per rubric pillar'),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('revision_requested', 'Revision Requested')], default='submitted', max_length=25),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('assignment', 'student')},
        ),
    ]
