# Generated by Django 5.2.7 on 2026-09-26 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_assignment_options_alter_submission_options_and_more'),
        ('scheduling', '0003_alter_batch_days_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSubjectTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batch_tutor_assignments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tutors', to='scheduling.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_tutors', to='courses.subject')),
                ('tutor', models.ForeignKey(limit_choices_to={'profile__role__in': ['instructor', 'hod']}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_batch_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Batch Subject Tutor',
                'verbose_name_plural': 'Batch Subject Tutors',
                'unique_together': {('batch', 'subject')},
            },
        ),
    ]
