# Generated by Django 5.2.7 on 2026-09-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_batchsubjecttutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_compulsory',
            field=models.BooleanField(default=True, help_text='Compulsory module automatically enrolled for all students.'),
        ),
    ]
