# Generated by Django 5.2.7 on 2026-04-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notified_sessions', models.IntegerField(default=0)),
            ],
        ),
    ]
