# Generated by Django 5.2.7 on 2026-09-22 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='billing_start_date',
            field=models.DateField(blank=True, help_text='Date when monthly billing commences.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Next scheduled monthly tuition due date.', null=True),
        ),
    ]
