# Generated by Django 5.2.7 on 2026-09-23 00:38

from decimal import Decimal
from django.db import migrations, models


def mark_existing_payments_approved(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Payment.objects.filter(amount_paid__gt=0).update(is_approved=True)

class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_billing_start_date_payment_next_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tuition discount, concession or scholarship waiver.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_reason',
            field=models.CharField(blank=True, default='', help_text='Reason for discount e.g. Early Bird, Sibling, Negotiated Rate', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approval by administrator/HOD before issuing receipt.'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Audit remarks or payment verification notes.'),
        ),
        migrations.RunPython(mark_existing_payments_approved, reverse_code=migrations.RunPython.noop),
    ]
