# Generated by Django 5.2.7 on 2026-09-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_approved_at_payment_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-issued_date']},
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_payment_date',
            field=models.DateField(blank=True, help_text='Date money was transferred/deposited in bank', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_month',
            field=models.CharField(db_index=True, default='September 2026', help_text='Academic billing month e.g. September 2026', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Attached bank payment receipt / teller / screenshot', null=True, upload_to='proofs/payments/'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_payment_date',
            field=models.DateField(blank=True, help_text='Date money was paid into the bank', null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='billing_month',
            field=models.CharField(default='September 2026', help_text='Billing month covered by this receipt', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_proof',
            field=models.FileField(blank=True, help_text='Archived bank proof attachment', null=True, upload_to='proofs/receipts/'),
        ),
    ]
