# Generated by Django 5.2.4 on 2026-07-22 21:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import teencamp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('mode', models.CharField(choices=[('PHYSICAL', 'Physical Class'), ('VIRTUAL', 'Virtual Class')], max_length=10)),
                ('camp_year', models.PositiveIntegerField(default=2026)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('current_size', models.PositiveIntegerField(default=0)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Lower numbers are filled first.')),
                ('accept_new_registrations', models.BooleanField(default=True)),
                ('reporting_time', models.TimeField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_days', models.CharField(help_text='Example: Mon, Wed & Fri', max_length=100)),
            ],
            options={
                'ordering': ['priority', 'code'],
                'unique_together': {('code', 'camp_year')},
            },
        ),
        migrations.CreateModel(
            name='CodingCampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(18)])),
                ('mode', models.CharField(choices=[('PHYSICAL', 'Physical Class'), ('VIRTUAL', 'Virtual Class')], default='PHYSICAL', max_length=10)),
                ('parent_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Guardian', 'Guardian'), ('Other', 'Other')], default='Guardian', max_length=20)),
                ('parent_phone', models.CharField(max_length=20)),
                ('parent_whatsapp', models.CharField(blank=True, max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('discount_applied', models.BooleanField(default=False)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.FileField(blank=True, null=True, upload_to=teencamp.models.receipt_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf'])])),
                ('payment_verified', models.BooleanField(default=False)),
                ('registration_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('BATCH_ASSIGNED', 'Batch Assigned'), ('SYNC_PENDING', 'Sync Pending'), ('SYNCED', 'Synced'), ('COMPLETED', 'Completed'), ('WAITLIST', 'Waiting List'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('camp_year', models.PositiveIntegerField(default=2026)),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('reg_code', models.CharField(editable=False, max_length=30, unique=True)),
                ('attendance_synced', models.BooleanField(default=False)),
                ('attendance_student_id', models.CharField(blank=True, max_length=30)),
                ('attendance_sync_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='teencamp.batch')),
            ],
            options={
                'verbose_name': 'Camp Registration',
                'verbose_name_plural': 'Camp Registrations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('first_name', 'last_name', 'parent_phone', 'camp_year'), name='unique_child_registration')],
            },
        ),
    ]
