# Generated by Django 5.2.4 on 2026-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teencamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='reserved_for_existing_students',
            field=models.BooleanField(default=False, help_text='Reserve this batch for existing CodeCamp students. New public registrations will not be allocated here.'),
        ),
    ]
