# Generated by Django 5.2.7 on 2026-08-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Academy or Organization name', max_length=150)),
                ('slug', models.SlugField(help_text='Subdomain or URL identifier', max_length=100, unique=True)),
                ('subdomain', models.CharField(blank=True, db_index=True, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this tenant is operational')),
                ('is_default', models.BooleanField(default=False, help_text='Default fallback tenant for unmatched requests')),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter Tier'), ('pro', 'Professional Tier'), ('enterprise', 'Enterprise Tier')], default='pro', max_length=20)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tenants/logos/')),
                ('theme_color', models.CharField(default='#1E3A8A', help_text='Primary brand color (hex)', max_length=20)),
                ('portal_title', models.CharField(blank=True, help_text='Custom brand header title', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default M2M Ingestion Key', help_text='Descriptive client label (e.g. Summer Camp Gateway, Kiosk Scanner)', max_length=100)),
                ('key', models.CharField(blank=True, db_index=True, max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant API Key',
                'verbose_name_plural': 'Tenant API Keys',
            },
        ),
        migrations.CreateModel(
            name='TenantDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, help_text='Custom domain or host (e.g. lagos.codecamp.org)', max_length=255, unique=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
            },
        ),
    ]
