# Generated by Django 5.2.7 on 2026-08-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.TextField(blank=True, help_text='Physical campus address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='max_students',
            field=models.PositiveIntegerField(default=500, help_text='Maximum allowed student accounts'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Lagos', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantdomain',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='DNS resolution status'),
        ),
    ]
