# Generated by Django 5.2.7 on 2026-08-07 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_address_tenant_max_students_tenant_timezone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantWebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='Destination HTTPS URL for real-time payloads', max_length=500)),
                ('secret', models.CharField(blank=True, help_text='HMAC secret for request payload verification', max_length=128)),
                ('events', models.CharField(default='attendance.all,student.enrolled', help_text='Comma-separated event topics (e.g. attendance.checkin, attendance.absent, student.enrolled)', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Webhook Endpoint',
                'verbose_name_plural': 'Tenant Webhook Endpoints',
            },
        ),
    ]
