# Generated by Django 5.2.7 on 2026-09-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantwebhookendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='director_name',
            field=models.CharField(default='Director of Academic Affairs', help_text='Name of director/signatory on official documents', max_length=150),
        ),
        migrations.AddField(
            model_name='tenant',
            name='director_signature',
            field=models.ImageField(blank=True, help_text='Official director signature image for certificates and receipts', null=True, upload_to='tenants/signatures/'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='director_title',
            field=models.CharField(default='Academic Director & Lead Instructor', help_text='Title shown below director signature', max_length=150),
        ),
    ]
